[package]
name = "cloud-cnc-bot/cura-engine"
version = "0.0.1-alpha.3"
description = "Ultimaker Cura Engine for Web Assembly"
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://github.com/Cloud-CNC/cura-engine.git"
homepage = "https://cloud-cnc.github.io"

# Standalone Cura Engine
[[module]]
name = "standalone"
source = "standalone.wasm"
abi = "wasi"

# Cura Engine with WASM callbacks
[[module]]
name = "callbacks"
source = "callbacks.wasm"
abi = "wasi"

[[command]]
name = "cura-engine"
module = "standalone"
