# Automated publishing for Cura Engine

name: Publish

on:
  # Run when a new release is created
  release:
    types:
      - published

jobs:
  # Publish Cura Engine to WAPM
  publish:
    name: Publish Cura Engine to WAPM
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v2

      # Setup Wasmer
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v1

      # Build the Docker image
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/build.dockerfile
          push: false
          tags: cloud-cnc/cura-engine

      # Run the Docker image
      - name: Run the Docker image
        uses: addnab/docker-run-action@v3
        with:
          image: cloud-cnc/cura-engine
          options: -v ${{ github.workspace }}/build:/root/cura-engine/build
          run: ./build.sh

      # Add package assets to the package directory
      - name: Add package assets
        run: |
          mkdir package
          sudo mv ./build/standalone.wasm ./package/standalone.wasm
          sudo mv ./build/callbacks.wasm ./package/callbacks.wasm
          mv ./README.md ./package
          mv ./wapm.toml ./package

      # Publish to WAPM
      - name: Publish to WAPM
        uses: wasmerio/wapm-publish@v1
        with:
          username: ${{ secrets.WAPM_USERNAME }}
          password: ${{ secrets.WAPM_PASSWORD }}
          directory: package